/* Automatically generated nanopb constant definitions */
/* Generated by 0.4.1-dev */

#include "mtpPlatino.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mtpPlatino_MSG_PHASE1_DRONE_ID, mtpPlatino_MSG_PHASE1_DRONE_ID, AUTO)


PB_BIND(mtpPlatino_MSG_PHASE1_ENDDEVICE_ID, mtpPlatino_MSG_PHASE1_ENDDEVICE_ID, AUTO)


PB_BIND(mtpPlatino_MSG_PHASE2_ENDDEVICE_DATA, mtpPlatino_MSG_PHASE2_ENDDEVICE_DATA, AUTO)


PB_BIND(mtpPlatino_MSG_PHASE2_DRONE_NACK, mtpPlatino_MSG_PHASE2_DRONE_NACK, AUTO)



