#!/bin/bash
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{"actionType": "append", "entities": [
        {
          "id":"urn:ngsi-ld:Home:001","type":"Home",
          "name":{"type":"Text","value":"Daniel House"}
        }
    ]
}'
