#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

printf "⏳ Provisioning IoT devices "


#
# Create a service groups for all UltraLight IoT devices
#

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "1068318794",
     "cbroker":     "http://orion:1026",
     "entity_type": "Thing",
     "resource":    "/iot/d"
   }
 ]
}'

####################################################
#
# Provision sensors for Store 001
#

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "sensor001",
     "entity_name": "Sensor:001",
     "entity_type": "Sensor",
     "timezone":    "Europe/Madrid",
     "attributes": [
     	{"object_id": "temp", "name": "temperature", "type": "Float"}
     ],
     "static_attributes": [
     	{"name": "refHome", "type": "Relationship", "value": "urn:ngsi-ld:Home:001"}
     ]
   }
  ]
}
'

echo -e " \033[1;32mdone\033[0m"
